# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 07:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('HELP_SELF', 'Helping self'), ('HELP_OTHERS', 'Helping others')], max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityPartCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('added_to_inventory', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('availability', models.TextField()),
                ('interests', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_number', models.CharField(max_length=100)),
                ('identifying_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('kind', models.CharField(choices=[('SB', 'Shop bike'), ('SCRAP', 'To be scrapped'), ('PB', 'Personal bike')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('consumable', models.BooleanField()),
                ('low_stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'skill categories',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('availability', models.TextField()),
                ('interests', models.TextField()),
                ('signed_form', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.SkillCategory'),
        ),
        migrations.AddField(
            model_name='activitypartcount',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Part'),
        ),
        migrations.AddField(
            model_name='activity',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Adult'),
        ),
        migrations.AddField(
            model_name='activity',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Bike'),
        ),
        migrations.AddField(
            model_name='activity',
            name='parts',
            field=models.ManyToManyField(through='byke.ActivityPartCount', to='byke.Part'),
        ),
        migrations.AddField(
            model_name='activity',
            name='skills',
            field=models.ManyToManyField(to='byke.Skill'),
        ),
        migrations.AddField(
            model_name='activity',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Stand'),
        ),
        migrations.AddField(
            model_name='activity',
            name='youth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Youth'),
        ),
    ]
