# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 01:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(blank=True, null=True)),
                ('low_stock', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('when_created', models.DateTimeField(default=datetime.datetime.now)),
                ('shop_number', models.CharField(blank=True, max_length=100)),
                ('identifying_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('for_scrap', models.BooleanField(default=False)),
                ('history', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('consumable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('availability', models.TextField()),
                ('interests', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('time_in', models.DateTimeField(default=datetime.datetime.now)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('HELP_SELF', 'Helping self'), ('HELP_OTHERS', 'Helping others')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'skill categories',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='byke.Person')),
            ],
            bases=('byke.person',),
        ),
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='byke.Person')),
                ('signed_form', models.BooleanField(default=False)),
            ],
            bases=('byke.person',),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.SkillCategory'),
        ),
        migrations.AddField(
            model_name='shopsession',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Person'),
        ),
        migrations.AddField(
            model_name='shopsession',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byke.Stand'),
        ),
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byke.Person'),
        ),
        migrations.AddField(
            model_name='activityskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Skill'),
        ),
        migrations.AddField(
            model_name='activitypart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.Part'),
        ),
        migrations.AddField(
            model_name='activity',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byke.Bike'),
        ),
        migrations.AddField(
            model_name='activity',
            name='parts',
            field=models.ManyToManyField(through='byke.ActivityPart', to='byke.Part'),
        ),
        migrations.AddField(
            model_name='activity',
            name='shop_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byke.ShopSession'),
        ),
        migrations.AddField(
            model_name='activity',
            name='skills',
            field=models.ManyToManyField(through='byke.ActivitySkill', to='byke.Skill'),
        ),
        migrations.AddField(
            model_name='activity',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='byke.Adult'),
        ),
    ]
