# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='when_created',
            new_name='when_added',
        ),
    ]
